# Runtime parameters
device: 'cuda'
use_pinn: true
use_mass: true
sample_with_replacement: false
sample_size: 1024

exp:
  name: 'klein_pca30_popsize'
  output_dir: 'results'

data:
  file_path: 'klein/klein_pca30_train.csv'
  dim: 30
  hold_one_out: false
  pop_mean: [30,000, 150,000, 450,000]  # adata.uns['pop']['mean'] for Day 2, 4, 6 # set to null if not using sequenced cell count

model:
  in_out_dim: 30
  hidden_dim: 400
  n_hiddens: 2
  activation: 'leakyrelu'
  score_hidden_dim: 128

pretrain:
  epochs: 500
  lr: 0.0001
  lambda_ot: 1.0
  lambda_mass: 0.01
  lambda_energy: 0.0

score_train:
  epochs: 3001
  lr: 0.0001
  lambda_penalty: 1
  sigma: 0.1
  score_batch_size: 512

train:
  epochs: 500
  lr: 0.0001
  lambda_ot: 10
  lambda_mass: 10
  lambda_energy: 0.01
  lambda_pinn: 100
  lambda_initial: 0.1
  scheduler_step_size: 100
  scheduler_gamma: 0.8

eval:
  n_points: 100
  n_trajectories: 30
  n_bins: 100
